Repository kubernetes-sigs/cli-experimental, pull requests merged in 2019-05, with the labels that each got.

#6 Adding dynamic-client interface
  Makefile
  go.mod
  go.sum
  internal/pkg/client/client.go
  internal/pkg/client/interface.go
  internal/pkg/dy/dy.go
  internal/pkg/wirecli/wire.go
  internal/pkg/wirecli/wirecli.go
  internal/pkg/wirecli/wirek8s/wirek8s.go
  internal/pkg/wirecli/wiretest/wiretest.go
  scripts/check-everything.sh
  scripts/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#7 Adding internal/pkg/client tests
  cmd/cmd.go
  go.mod
  go.sum
  internal/pkg/client/client.go
  internal/pkg/client/client_suite_test.go
  internal/pkg/client/client_test.go
  internal/pkg/client/interface.go
  internal/pkg/client/patch/patch.go
  internal/pkg/client/patch/patch_suite_test.go
  internal/pkg/client/patch/patch_test.go
  internal/pkg/client/patch/scheme.go
  internal/pkg/dy/dispatch/dispatch.go
  internal/pkg/wirecli/wirek8s/wirek8s.go
Labels: cncf-cla: yes, lgtm, size/XXL

#11 add InitializeFakeCmd and use it in test
  go.mod
  go.sum
  pkg/cmd_test.go
  pkg/wire.go
  pkg/wire_gen.go
  pkg/wirepkg.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#8 add approvers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9 implement RawConfigFileProvider
  internal/pkg/resourceconfig/resourceconfig.go
  internal/pkg/resourceconfig/resourceconfig_test.go
  internal/pkg/wirecli/wireconfig/wireconfig.go
  internal/pkg/wirecli/wiretest/wire.go
  internal/pkg/wirecli/wiretest/wire_gen.go
Labels: approved, cncf-cla: yes, lgtm, size/L
