Repository kubernetes-sigs/cli-experimental, pull requests merged in 2019-06, with the labels that each got.

#12 Some improvements for Makefile
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#14 Adding status command
  Makefile
  cmd/apply/status/status.go
  cmd/apply/status/status_test.go
  cmd/test-manifests/hello/configmap.yaml
  cmd/test-manifests/hello/deployment.yaml
  cmd/test-manifests/hello/kustomization.yaml
  cmd/test-manifests/hello/pod.yaml
  cmd/test-manifests/hello/statefulset.yaml
  go.mod
  go.sum
  internal/pkg/apply/apply.go
  internal/pkg/client/client.go
  internal/pkg/client/unstructured/doc.go
  internal/pkg/client/unstructured/helpers.go
  internal/pkg/client/unstructured/helpers_test.go
  internal/pkg/status/doc.go
  internal/pkg/status/generic_status.go
  internal/pkg/status/legacy_status.go
  internal/pkg/status/status.go
  internal/pkg/status/status_test.go
  internal/pkg/wirecli/wireapply/wire_gen.go
  internal/pkg/wirecli/wirestatus/wire.go
  internal/pkg/wirecli/wirestatus/wire_gen.go
  internal/pkg/wirecli/wirestatus/wirestatus.go
  internal/pkg/wirecli/wiretest/wire_gen.go
  pkg/cmd.go
  pkg/cmd_test.go
  pkg/wire_gen.go
  pkg/wirepkg.go
  scripts/manual-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#16 cmd/status test failure fix
  cmd/apply/apply.go
  cmd/apply/status/status.go
  cmd/apply/status/status_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#15 fix generate failure
  internal/pkg/status/legacy_status.go
  internal/pkg/status/status_test.go
  internal/pkg/wirecli/wireapply/wire_gen.go
  internal/pkg/wirecli/wirestatus/wire.go
  pkg/cmd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#17 update kustomize to 2.1.0 and fix the resource ordering issue
  cmd/apply/status/status_test.go
  go.mod
  go.sum
  internal/pkg/apply/apply.go
  internal/pkg/delete/delete.go
  internal/pkg/prune/prune.go
  internal/pkg/resourceconfig/resourceconfig.go
  internal/pkg/resourceconfig/resourceconfig_test.go
  internal/pkg/wirecli/wireconfig/wireconfig.go
  pkg/cmd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
