Repository kubernetes-sigs/cli-experimental, pull requests merged in 2021-06, with the labels that each got.

#173 Fix kustomize replicas sample code
  site/content/en/references/kustomize/kustomization/replicas/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 docs(eschewedfeatures.md): fix broken links
  site/content/en/faq/kustomize/eschewedfeatures.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#172 Update multi_base.md
  site/content/en/guides/example/multi_base.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 docs(versioningPolicy.md): fix broken links
  site/content/en/faq/kustomize/versioningPolicy.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 replacements documentation
  site/content/en/references/kustomize/kustomization/replacements/_index.md
  site/content/en/references/kustomize/kustomization/vars/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#104 Fix typos in builtins.md
  site/content/en/guides/extending_kustomize/builtins.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#113 align namePrefix example with others
  site/content/en/references/kustomize/kustomization/nameprefix/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#97 Fix a syntax error in the use of from env file
  site/content/en/references/kustomize/kustomization/configmapgenerator/_index.md
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/XS

#183 Add different strategies examples for kustomize patches fields
  site/content/en/references/kustomize/kustomization/patches/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#98 Update _index.md
  site/content/en/references/kubectl/create/configMap/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#132 Update the link to Components KEP page
  site/content/en/guides/config_management/components.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#186 Fix "conatiner" typo
  site/content/en/references/kustomize/kustomization/nameprefix/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
