Repository kubernetes-sigs/cli-experimental, pull requests merged in 2021-05, with the labels that each got.

#151 Remove extraneous backslash
  site/content/en/installation/kustomize/binaries.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#152 fix plugins link
  site/content/en/references/kustomize/glossary/_index.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, do-not-merge/invalid-commit-message, lgtm, size/XS

#157 Update README.md
  site/README.md
Labels: cncf-cla: yes, size/XS

#161 Fix Build Output
  site/content/en/references/kustomize/kustomization/nameprefix/_index.md
Labels: cncf-cla: yes, size/XS

#162 upgrade go
  .travis.yml
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS

#168 Tidy the go.mod files.
  go.mod
  go.sum
  site/go.mod
  site/go.sum
Labels: approved, cncf-cla: yes, size/L

#169 Fix travis build.
  .travis.yml
  go.mod
  go.sum
  scripts/check-everything.sh
  scripts/common.sh
  scripts/test-all.sh
  scripts/verify.sh
Labels: approved, cncf-cla: yes, size/XL
