Repository kubernetes-sigs/cli-experimental, pull requests merged in 2022-03, with the labels that each got.

#245 add file-based configuration for netlify
  .gitignore
  netlify.toml
  site/config.toml
  site/content/en/contributing/docs/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#254 docs: add immutable flag for generatorOptions
  site/content/en/references/kustomize/kustomization/generatoroptions/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#253 fix broken links in guides
  site/content/en/guides/config_management/container_images.md
  site/content/en/guides/config_management/labels_annotations.md
  site/content/en/guides/config_management/namespaces_names.md
  site/content/en/guides/config_management/secrets_configmaps.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#249 site/kustomize: fix resource hyperlink to base
  site/content/en/references/kustomize/kustomization/bases/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#248 Add extended examples for patchesjson6902 documentation
  site/content/en/references/kustomize/kustomization/patchesjson6902/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#240 docs: replacements to all array elements
  site/content/en/references/kustomize/kustomization/replacements/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#261 Fix issue #260
  site/content/en/installation/kubectl/binaries.md
Labels: cncf-cla: yes, lgtm, size/M, approved
