Repository kubernetes-sigs/cli-experimental, pull requests merged in 2022-07, with the labels that each got.

#283 fix dead link
  site/content/en/references/kustomize/kustomization/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#284 add more details about helm support to kustomize docs
  site/content/en/references/kustomize/kustomization/helmcharts/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved, tide/merge-method-squash

#268 Add doc for includeSelectors flag
  site/content/en/references/kustomize/kustomization/labels/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#290 Add docs for new advanced NamespaceTransformer config options
  site/content/en/references/kustomize/builtins/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S
