Repository kubernetes-sigs/cli-experimental, pull requests merged in 2022-02, with the labels that each got.

#231 provide job under kubectl create
  site/content/en/references/kubectl/create/job/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#62 Fixes misspelling of container.
  site/content/en/references/kubectl/apply/_index.md
Labels: lifecycle/rotten, cncf-cla: yes, lgtm, approved, size/XS

#133 docs(kustomize-secretgenerator): fix tls secrets
  site/content/en/references/kustomize/kustomization/secretgenerator/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#202 Minor grammar nits
  site/content/en/references/kustomize/kustomization/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#214 docs: fix broken link
  site/content/en/references/kustomize/kustomization/secretgenerator/_index.md
Labels: cncf-cla: yes, lgtm, lifecycle/stale, approved, size/XS

#203 Update _index.md
  site/content/en/_index.md
Labels: lifecycle/rotten, cncf-cla: yes, lgtm, approved, size/XS

#225 fix indentation
  site/content/en/references/kustomize/builtins/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S

#239 Update quoted title to be relevant with content
  site/content/en/guides/introduction/resources_controllers.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#241 Update Go Source install doc to v4
  site/content/en/installation/kustomize/source.md
Labels: cncf-cla: yes, lgtm, approved, size/XS
