Repository kubernetes-sigs/cli-experimental, pull requests merged in 2022-08, with the labels that each got.

#275 Update source.md
  site/content/en/installation/kustomize/source.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#292 Fix symbols
  site/content/en/installation/kustomize/source.md
Labels: cncf-cla: yes, approved, size/XS

#228 Update _index.md
  site/content/en/references/kustomize/builtins/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#293 Add note about custom resource + SMPs
  site/content/en/references/kustomize/kustomization/patches/_index.md
  site/content/en/references/kustomize/kustomization/patchesStrategicMerge/_index.md
Labels: cncf-cla: yes, lgtm, approved, size/S
