Repository kubernetes-sigs/cli-experimental, pull requests merged in 2023-02, with the labels that each got.

#306 Document sortOptions field
  site/content/en/references/kustomize/kustomization/sortoptions/_index.md
  site/content/en/references/kustomize/kustomization/vars/_index.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#313 Add `kustomize localize` Documentation
  site/content/en/references/kustomize/cmd/localize/_index.md
Labels: cncf-cla: yes, lgtm, size/L, approved

#289 kustomize: add deprecation warning to docs
  site/content/en/references/kustomize/kustomization/bases/_index.md
  site/content/en/references/kustomize/kustomization/patchesStrategicMerge/_index.md
  site/content/en/references/kustomize/kustomization/patchesjson6902/_index.md
  site/content/en/references/kustomize/kustomization/vars/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#314 Update references for kustomize v5
  site/content/en/faq/kustomize/_index.md
  site/content/en/installation/kustomize/docker.md
  site/content/en/installation/kustomize/source.md
  site/content/en/references/kustomize/cmd/version/_index.md
  site/content/zh/faq/_index.md
Labels: cncf-cla: yes, lgtm, size/M, approved

#324 docs: remove warning about ARM support for Kustomize install script
  site/content/en/installation/kustomize/binaries.md
Labels: cncf-cla: yes, lgtm, approved, size/XS

#321 fix: Small doc typos
  site/content/en/guides/app_deployment/publishing_bases.md
  site/content/en/guides/container_debugging/container_logs.md
  site/content/en/guides/container_debugging/copying_container_files.md
  site/content/en/guides/container_debugging/port_forward_to_pods.md
Labels: cncf-cla: yes, lgtm, approved, size/XS
